# GitHub Actions
# https://docs.github.com/en/actions/using-workflows
name: Cypress single tests

on: [push, workflow_dispatch]

jobs:
  test1:
    name: Cypress test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      # just so we learn about available environment variables GitHub provides
      - name: Print env variables
        run: |
          npm i -g @bahmutov/print-env
          print-env GITHUB

      # Restore the previous npm modules and Cypress binary archives.
      # In case there's no previous cache the packages will be downloaded
      # and saved automatically after the entire workflow successfully finishes.
      # See https://github.com/actions/cache
      - name: Cache node modules
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Cache Cypress binary
        uses: actions/cache@v5
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies and verify Cypress
        env:
          # make sure every Cypress install prints minimal information
          CI: 1
        # print Cypress and OS info
        run: |
          npm ci
          npx cypress verify
          npx cypress info
          npx cypress version
          npx cypress version --component package
          npx cypress version --component binary
          npx cypress version --component electron
          npx cypress version --component node

      # Starts local server, runs Cypress tests, saves output, and kills server when done
      - name: Cypress tests
        run: npm run test:ci | tee test-results.txt
        env:
          TERM: xterm
          NO_COLOR: 1
      # Save screenshots as test artifacts
      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots

      # Safely package the text result into JSON and send to n8n
      - name: Send Result to n8n
        if: always()
        run: |
          jq -n \
            --arg status "${{ job.status }}" \
            --arg run_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --rawfile results test-results.txt \
            '{status: $status, run_url: $run_url, text_result: $results}' > n8n_payload.json

          curl -X POST "https://zaidrad4910.app.n8n.cloud/webhook-test/acd68b24-1b73-4497-8427-0b596d18a0ca" \
          -H "Content-Type: application/json" \
          -d @n8n_payload.json